spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://ehr-postgres:5432/hapi
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
      hibernate.format_sql: false
      hibernate.show_sql: false
  flyway:
    enabled: false

hapi:
  fhir:
    fhir_version: DSTU3
    server_address: http://localhost:8080/fhir
    allow_external_references: true
    expunge_enabled: true
    allow_cascading_deletes: true
    narrative_enabled: true
    default_encoding: JSON
    default_pretty_print: true
    tester:
      - id: home
        name: "Internal HAPI Server"
        server_address: "http://localhost:8080/fhir"
        fhir_version: DSTU3
    validation:
      requests_enabled: false
      responses_enabled: false
    cors:
      allow_credentials: true
      allowed_origin:
        - "*"
      allowed_header:
        - "*"
      allowed_method:
        - "*"
    binary_storage_enabled: false
    subscription:
      resthook_enabled: false
      websocket_enabled: false
